name: senturionscaleg
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  # necessario para gravar chaves valores
  shared_preferences: ^2.3.2
  #utilizado para gerar pdf
  pdf: ^3.10.1
  #utilizado para salvar
  # pdf no celular
  path_provider: ^2.0.14
  open_file: ^3.2.1
  # utilizado para salvar
  # pdf na web
  universal_html: ^2.2.1
  # necessario para notificacao elegante
  elegant_notification: ^2.2.2
  # necessario para rodar firebase
  firebase_database: ^11.1.0
  cloud_firestore: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagens/

